version: '3'

services:

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=herodb
      - POSTGRES_USER=herodb
      - POSTGRES_PASSWORD=herodb
      - MAX_CONNECTIONS=300
